/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BTN_5_aliases.h"
#include "BTN_5.h"
#include "BTN_4_aliases.h"
#include "BTN_4.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "USBFS_1_cydmac.h"
#include "USBFS_1_msc.h"
#include "BTN_3_aliases.h"
#include "BTN_3.h"
#include "BTN_2_aliases.h"
#include "BTN_2.h"
#include "BTN_1_aliases.h"
#include "BTN_1.h"
#include "SW_D_aliases.h"
#include "SW_D.h"
#include "SW_C_aliases.h"
#include "SW_C.h"
#include "SW_B_aliases.h"
#include "SW_B.h"
#include "SW_A_aliases.h"
#include "SW_A.h"
#include "BTN_6_aliases.h"
#include "BTN_6.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dp_aliases.h"
#include "USBFS_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

