/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "C1_aliases.h"
#include "C1.h"
#include "C2_aliases.h"
#include "C2.h"
#include "C3_aliases.h"
#include "C3.h"
#include "C4_aliases.h"
#include "C4.h"
#include "LCD_Char_1.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "USBFS_1_cydmac.h"
#include "USBFS_1_msc.h"
#include "C5_aliases.h"
#include "C5.h"
#include "AP_aliases.h"
#include "AP.h"
#include "AL_aliases.h"
#include "AL.h"
#include "AH_aliases.h"
#include "AH.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "R4L_aliases.h"
#include "R4L.h"
#include "R3L_aliases.h"
#include "R3L.h"
#include "R4R_aliases.h"
#include "R4R.h"
#include "R3R_aliases.h"
#include "R3R.h"
#include "R2R_aliases.h"
#include "R2R.h"
#include "R2L_aliases.h"
#include "R2L.h"
#include "R1_aliases.h"
#include "R1.h"
#include "U3_aliases.h"
#include "U3.h"
#include "U1_aliases.h"
#include "U1.h"
#include "U2_aliases.h"
#include "U2.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dp_aliases.h"
#include "USBFS_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

