# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\aztec\OneDrive\Documents\PSoC Creator\test2\CE195394_HID_Mouse\CE195394_HID_Mouse.cydsn\CE195394_HID_Mouse.cyprj
# Date: Sat, 01 Mar 2025 00:11:08 GMT
#set_units -time ns


# Component constraints for C:\Users\aztec\OneDrive\Documents\PSoC Creator\test2\CE195394_HID_Mouse\CE195394_HID_Mouse.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\aztec\OneDrive\Documents\PSoC Creator\test2\CE195394_HID_Mouse\CE195394_HID_Mouse.cydsn\CE195394_HID_Mouse.cyprj
# Date: Sat, 01 Mar 2025 00:11:05 GMT
